### PR TITLE
Fix #563 - Make it an error when the typings become incorrect

### LINKED ISSUE #563: Type inference issues caused by default param values or any/unknown type (v4.1.5)
I encountered two issues with type inference in v4.1.5:

1. When an input-selector expects more than one param and the last param is typed as unknown/any, TS complains that the final selector expect 1 param instead of 2.

2. When a default value is provided to any param of at least one input-selector without providing a type explicitly, all params to an output-selector are implicitly typed as any. 

This code sandbox shows the issue: https://codesandbox.io/s/reselect-ts-issues-opbhs?file=/src/index.ts:272-279

### PR DESCRIPTION
**Pull request by lukeapage**
I've taken my Pr - https://github.com/reduxjs/reselect/pull/564 and simplified the change to only remove the condition that breaks. 

It is incorrect because when a problem happens with params, `[never]` extends `[EmptyObject]` and `RemainingItems` becomes `[never]`. 

But when we get to OutputSelector
```
export type OutputSelector<
  S extends SelectorArray,
  Result,
  Combiner extends UnknownFunction,
  Params extends readonly any[] = never // MergeParameters<S>
> = Selector<GetStateFromSelectors<S>, Result, Params> &
  OutputSelectorFields<Combiner>
```

never is the default to mean that there should not be any params (e.g. no problem at all, rather than [never] which means there is a type problem - there is 1 parameter of value never, which then will error with no params and error with 1 param).

The alternative fix requires alot of changes and this simple fix does not break any existing test cases.

@markerikson I will comment on the Pr which pieces of the test case I added are different on master.

I hope this new Pr is easier to review.

### CODE REVIEW

File: typescript_test/test.ts [hunk 1]
```diff
@@ -580,6 +580,104 @@ function testArrayArgument() {
...
+    (state: State, arg: string) => arg,
+    (state: State, arg: number) => arg,
+    (baz) => {
+      const baz1: boolean = baz
+      // @ts-expect-error
+      const baz2: number = baz
+    }
+  )
+
+  // @ts-expect-error the selector above has inconsistent conflicting arguments so usage should error
```
Comment (lukeapage) [inline typescript_test/test.ts:597]: on master there is no error - even though we expect a parameter, we are allowed to call it without one

File: typescript_test/test.ts [hunk 2]
```diff
@@ -580,6 +580,104 @@ function testArrayArgument() {
...
+  // @ts-expect-error
+  selector({} as State, 1)
+
+  const selector2 = createSelector(
+    (state: State, prefix: any) => prefix + state.foo,
+    (str) => str
+  )
+
+  // @ts-expect-error here we require one argument which can be anything so error if there are no arguments
+  selector2({} as State)
```
Comment (lukeapage) [inline typescript_test/test.ts:610]: on master there is no error, again, we require a parameter but none is passed in

File: typescript_test/test.ts [hunk 3]
```diff
@@ -580,6 +580,115 @@ function testArrayArgument() {
...
+  selector7({} as State, 'blach')
+  // @ts-expect-error wrong type
+  selector7({} as State, 1)
+
+  const selector8 = createSelector(
+    (state: State, prefix: unknown) => prefix,
+    (str) => str
+  )
+
+  // @ts-expect-error needs a argument
```
Comment (lukeapage) [inline typescript_test/test.ts:685]: this error does not occur on master

**Comment by markerikson** [comment]
Thanks, I'll _try_ to take a look at this in the next few days, but also have some other things I need to get done first.

**Comment by markerikson** [comment]
For the record I haven't forgotten about this :)  But I've been really busy with a bunch of other things and haven't had time to do general Redux issue-related work.

Still high on my list to look at as soon as I have time...

**Comment by lukeapage** [comment]
Thanks @markerikson I have been watching the redux / toolkit releases and figures as much, I’m a burnt out open source maintainer myself so I understand.

typescript next failed but I suspect master is broken, will try to take a look soon.

**Comment by markerikson** [comment]
I think the TS error there is actually related to something on the RTK side - we've been seeing the same errors in the RTK repo, I think.

**Comment by markerikson** [comment]
Okay, this seems reasonable.  I'll merge and see if there's any other tweaks worth doing before publishing 4.1.6

**Comment by markerikson** [comment]
Hmm. So I opened this up in VS Code Web and didn't immediately see errors, so I merged it. But, when I pulled `master` locally and opened up `types.ts`, I'm seeing a couple TS errors in the changes you added, using TS 4.5.  So, I'm kinda confused.  Can you review the changes on your side?  

Specifically, I'm seeing errors with:

```ts
function testConnect() {
  connect(
    createSelector(
      (state: { foo: string }) => state.foo,
      foo => ({ foo })
    )
  )
```

and:

```ts
  // ------  ISSUE 1 ------

  const selector = createSelector(
    (state: State, prefix: unknown) => prefix + state.text,
    str => str //          ^ unknown or any cause the error below
  )

  selector(exampleState, 'blach')
```

**Comment by lukeapage** [comment]
I can check tomorrow, it’s late here in Denmark

**Comment by lukeapage** [comment]
Hi @markerikson,

I've tried TS 4.4, 4.5 and 4.6 - for each I reloaded my editor (webstorm) and waited for TS errors and also ran `yarn test:typescript` and I cannot see the problem you are talking about.. Can you give me more info and check it is not a local issue for you?

**Comment by markerikson** [comment]
Whoops, I apologize!  I had apparently doing a bit of experimenting the last time I touched the Reselect repo several weeks ago, and had some changes on disk that weren't committed and weren't relevant.  When I did a `git pull`, those caused conflicts and the pull didn't get checked out, so I was actually looking at the same uncommitted code I had already.

If I ditch those changes, the file looks clean.

**Comment by lukeapage** [comment]
@markerikson any chance we can have a new release to be able to consume this? I'm happy to be tagged if it results in issues for others when they consume it.

**Comment by markerikson** [comment]
Yeah, sorry, been busy with a bunch of other things.  I'll try to push out a new build this weekend.

**Comment by markerikson** [comment]
@lukeapage Okay, this is _finally_ live in https://github.com/reduxjs/reselect/releases/tag/v4.1.6 . Thanks for the work and the nudges here!

(And if you have any other ideas for improving the types, please feel free to file more PRs - always interested in making things better!)
